### ISSUE TITLE
Performance regression for overhead in `compileAndRun`

### ISSUE THREAD

**Issue by ggeorgakoudis** [Olympus-HPC/proteus#59]
For convenience we extract the types of runtime arguments from the bitcode. This means every time we need to parse the IR and extract them. We should avoid this overhead

**Comment by koparasy** [comment]
@ggeorgakoudis my suggestion would be that you add a __jit_register_function interface call.

The function would look like:

void __jit_register_function(void* stubAddr, enum ProteusDTypes *DataTypes, bool *JitArguments, int size);

Which assocaiates a stubAddr with the function's datatypes and also passes the information regarding the constant arguments.
