### ISSUE TITLE
Fix halo packing compilation error

### ISSUE THREAD

**Issue by johnbowen42** [Olympus-HPC/proteus#67]
The  [HALO_PACKING](https://github.com/Olympus-HPC/RAJAPerf/blob/develop/src/comm/HALO_PACKING.cpp) benchmark in the RAJA performance suite currently does not compile with a JIT-annotated `forall_impl`.  Compilation indicates an unterminated basic block and broken LLVM module.

**Comment by johnbowen42** [comment]
this is not fixed by #74

**Comment by ggeorgakoudis** [comment]
What is your issue? We tested successfully with @davidbeckingsale.

**Comment by johnbowen42** [comment]
I had some cmake issues that were still causing failures
